[package]
name = "sui_dev_token"
version = "0.0.4"
published-at = "0xd175cff04f1d49574efb6f138bc3b9b7313915a57b5ca04141fb1cb4f66984b2"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }

[addresses]
sui_dev_token =  "0x0"
sui =  "0x2"
